name: RSpec
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          cache-version: 1
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0
      - name: Check if ES is running
        run: curl localhost:9200
      - name: Run Webpacker
        run: |
          bundle exec rake assets:precompile
      - name: List all files
        run: ls
      - name: Run rspec
        run: bundle exec rspec
