name: RSpec
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:6.8.3
        ports:
        - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Check ruby version
        run: |
          ruby -v
          echo "${job.services.elasticsearch.ports[9200]}"
      - name: Install Bundler
        run: |
          gem install bundler
      - name: Run Bundle
        run: bundle install
      - name: List all files
        run: ls
      - name: Run rspec
        run: bundle exec rspec

