name: RSpec
on:
  push:
jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0
      - name: Check if ES is running
        run: curl localhost:9200
      - name: Check ruby version
        run: |
          ruby -v
      - name: Install Bundler
        run: |
          gem install bundler
      - name: Run Bundle
        run: bundle install
      - name: Setup DB
        run: rake db:setup
      - name: List all files
        run: ls
      - name: Run rspec
        run: bundle exec rspec
